#ifndef MODEL_H
#define MODEL_H

#define MODEL_RESOURCE_NOT_FOUND -5
#define MODEL_EMPTY_RESOURCE -4
#define MODEL_DEALLOC_ERR -3
#define MODEL_REALLOC_ERR -2
#define MODEL_OP_ERR -1
#define MODEL_OP_SUCCESS 0

#endif //MODEL_H
